# Generated by Django 6.1.1 on 2026-09-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('debit', 'Debit card'), ('wallet', 'Wallet card'), ('cod', 'Cash on delivery')], default='cod', max_length=20),
        ),
    ]
